# postgres Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: xyzmaps/xyz-postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            # The :z option isn't required in Kubernetes for volumes
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 2
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

# redis Deployment and Service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

# xyz-hub Deployment and Service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyz-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xyz-hub
  template:
    metadata:
      labels:
        app: xyz-hub
    spec:
      containers:
        - name: xyz-hub
          image: xyzmaps/xyz-hub
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: REDIS_HOST
              value: redis
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: xyz-hub
spec:
  selector:
    app: xyz-hub
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

# xyz-gateway Deployment and Service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyz-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xyz-gateway
  template:
    metadata:
      labels:
        app: xyz-gateway
    spec:
      containers:
        - name: xyz-gateway
          image: xyzmaps/xyz-gateway
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: xyz-gateway
spec:
  selector:
    app: xyz-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

# Optional: docs Deployment and Service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyz-docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xyz-docs
  template:
    metadata:
      labels:
        app: xyz-docs
    spec:
      containers:
        - name: xyz-docs
          image: xyzmaps/xyz-docs
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: xyz-docs
spec:
  selector:
    app: xyz-docs
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 80

# Optional: swagger-ui Deployment and Service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-ui
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      containers:
        - name: swagger-ui
          image: swaggerapi/swagger-ui
          ports:
            - containerPort: 8080
          env:
            - name: SWAGGER_JSON_URL
              value: http://xyz-gateway:8080/hub/static/openapi/stable.yaml

---
apiVersion: v1
kind: Service
metadata:
  name: swagger-ui
spec:
  selector:
    app: swagger-ui
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8080

# Optional: redoc-ui Deployment and Service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redoc-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redoc-ui
  template:
    metadata:
      labels:
        app: redoc-ui
    spec:
      containers:
        - name: redoc-ui
          image: redocly/redoc
          ports:
            - containerPort: 80
          env:
            - name: SPEC_URL
              value: http://xyz-gateway:8080/hub/static/openapi/stable.yaml

---
apiVersion: v1
kind: Service
metadata:
  name: redoc-ui
spec:
  selector:
    app: redoc-ui
  ports:
    - protocol: TCP
      port: 8889
      targetPort: 80