# podman kube file for using as systemd service
# for local testing with pre-built images run `podman play kube --build=false xyz-pod.yml`

apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  containers:
    - name: postgres
      image: docker.io/xyzmaps/xyz-postgres
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      securityContext:
        runAsUser: 999  # Placeholder for "keep-id" equivalent
      env:
        - name: POSTGRES_USER
          value: postgres  # Example for healthcheck
      startupProbe:  # Converted healthcheck
        exec:
          command:
            - pg_isready
            - -U
            - postgres
        initialDelaySeconds: 20
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 2
  volumes:
    - name: postgres-data
      persistentVolumeClaim:
        claimName: postgres-volume-claim

---
apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
    - name: redis
      image: docker.io/redis

---
apiVersion: v1
kind: Pod
metadata:
  name: xyz-hub
spec:
  containers:
    - name: xyz-hub
      image: docker.io/xyzmaps/xyz-hub

---
apiVersion: v1
kind: Pod
metadata:
  name: xyz-gateway
spec:
  containers:
    - name: xyz-gateway
      image: docker.io/xyzmaps/xyz-gateway
      ports:
        - containerPort: 8080
          hostPort: 8080

---
apiVersion: v1
kind: Pod
metadata:
  name: docs
spec:
  containers:
    - name: docs
      image: docker.io/xyzmaps/xyz-docs
      ports:
        - containerPort: 80
          hostPort: 9000

---
apiVersion: v1
kind: Pod
metadata:
  name: swagger-ui
spec:
  containers:
    - name: swagger-ui
      image: docker.io/swaggerapi/swagger-ui
      ports:
        - containerPort: 8080
          hostPort: 8888
      env:
        - name: SWAGGER_JSON_URL
          value: http://localhost:8080/hub/static/openapi/stable.yaml

---
apiVersion: v1
kind: Pod
metadata:
  name: redoc-ui
spec:
  containers:
    - name: redoc-ui
      image: docker.io/redocly/redoc
      ports:
        - containerPort: 80
          hostPort: 8889
      env:
        - name: SPEC_URL
          value: http://localhost:8080/hub/static/openapi/stable.yaml